/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/* GPIO_B1_15 (coord B14), GIO2_31 */
/* Routed pin properties */
#define BOARD_INITPINS_GIO2_31_PERIPHERAL                                  GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_GIO2_31_SIGNAL                                    gpio_io   /*!< Signal name */
#define BOARD_INITPINS_GIO2_31_CHANNEL                                       31U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_GIO2_31_GPIO                                        GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_GIO2_31_GPIO_PIN                                      31U   /*!< GPIO pin number */
#define BOARD_INITPINS_GIO2_31_GPIO_PIN_MASK                         (1U << 31U)   /*!< GPIO pin mask */

/* PMIC_ON_REQ (coord K7), PMIC_ON_REQ */
/* Routed pin properties */
#define BOARD_INITPINS_PMIC_ON_REQ_PERIPHERAL                              GPIO5   /*!< Peripheral name */
#define BOARD_INITPINS_PMIC_ON_REQ_SIGNAL                                gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PMIC_ON_REQ_CHANNEL                                    1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PMIC_ON_REQ_GPIO                                    GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PMIC_ON_REQ_GPIO_PIN                                   1U   /*!< GPIO pin number */
#define BOARD_INITPINS_PMIC_ON_REQ_GPIO_PIN_MASK                      (1U << 1U)   /*!< GPIO pin mask */

/* PMIC_STBY_REQ (coord L7), PMIC_STBY_REQ */
/* Routed pin properties */
#define BOARD_INITPINS_PMIC_STBY_REQ_PERIPHERAL                            GPIO5   /*!< Peripheral name */
#define BOARD_INITPINS_PMIC_STBY_REQ_SIGNAL                              gpio_io   /*!< Signal name */
#define BOARD_INITPINS_PMIC_STBY_REQ_CHANNEL                                  2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_PMIC_STBY_REQ_GPIO                                  GPIO5   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_PMIC_STBY_REQ_GPIO_PIN                                 2U   /*!< GPIO pin number */
#define BOARD_INITPINS_PMIC_STBY_REQ_GPIO_PIN_MASK                    (1U << 2U)   /*!< GPIO pin mask */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
